### ISSUE TITLE
Specifying a path with "" that ends with \ leads Dogscepter to escape the quote

### ISSUE THREAD

**Issue by Miepee** [colinator27/DogScepter#21]
For example, having ` .\DogScepterCLI.exe dump "data.win" -o "longPath\foobar\" -v --textures --strings --code --rooms` will cause dogscepter to use `longPath\foobar -v --textures --strings --code --rooms` as the path instead.

**Comment by colinator27** [comment]
This is actually normal behavior of the command line, so I don't think DogScepter has any control over it. However, it might be a good idea to properly validate the path.

**Comment by Miepee** [comment]
Hmm, that is strange.
Other command line tools (like `dir`) don't interpret the last backslash as an escape character.

**Comment by Miepee** [comment]
Upon further inspection, this is an issue of CliFX and not of DogScepter. Thus closing.
